spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/sales?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: none
      

  security:
    oauth2:
      client:
        registration:
          github:
            client-id:  Iv1.287cfdf698c98cb8
            client-secret: e5085c4ace2ac84ab51bf39abd9226ae6d78f3ba